### ISSUE TITLE
Toolbar items overlap some UI elements.

### ISSUE THREAD

**Issue by TobyTobyReal** [refact0r/midnight-discord#27] opened 2023-08-22 22:05 UTC
![1](https://github.com/refact0r/midnight-discord/assets/89554080/b23ffbbb-1b5b-4f98-aaff-7a7820fbf8cc)
![2](https://github.com/refact0r/midnight-discord/assets/89554080/7c69af69-281f-4a88-bf55-000d167f4bc3)

**Comment by refact0r** [comment] 2023-08-23 05:05
Have you modified the theme or added extra css? The help (?) toolbar button is supposed to be hidden by default.

**Comment by TobyTobyReal** [comment] 2023-08-25 23:48
Nope not at all.

**Comment by refact0r** [comment] 2023-08-26 03:24
I'm not seeing this on vencord or vesktop. What client mod and discord version are you using?

**Comment by TobyTobyReal** [comment] 2023-08-26 08:35
i've used vencord when i noticed this bug, now im using better discord.

**Comment by refact0r** [comment] 2023-08-26 22:07
I don't see this on betterdiscord either. Do you have any plugins? Also, make sure you have the latest version of the theme.

**Comment by Alx-x** [comment] 2023-08-28 19:30
It is caused by the chosen discord language. You are using a polish version of discord on which it is bugged.

**Comment by refact0r** [comment] 2023-08-28 23:49
Ah I forgot about that, the aria-labels are the only way to uniquely identify those buttons, so they don't work in other languages. I will try to use some other method, but for now you can just change the aria-label selectors in the code.

**Comment by refact0r** [comment] 2023-10-27 01:47
should be resolved in the latest update, i have used a method other than aria-labels.

**Closed by refact0r** 2023-10-27 01:47 UTC
